export const HEADER_STYLES = {
  container: "mx-auto flex w-full max-w-[1600px] items-center justify-between px-6 py-3",
  navBase: "hidden items-center gap-3 text-[0.9rem] uppercase tracking-[1.6px] text-[var(--muted)] min-[721px]:flex",
  navLinkBase: "rounded-full border px-3 py-1 transition duration-200",
  navLinkActive: "border-[var(--accent)] bg-[var(--chip-active-bg)] text-[var(--ink)]",
  navLinkInactive: "border-transparent hover:border-[var(--stroke)] hover:text-[var(--ink)]",
  authButtonGhost: "rounded-full border border-[var(--stroke)] px-4 py-1.5 text-[0.8rem] uppercase tracking-[1px] text-[var(--ink)] transition hover:border-[var(--stroke-strong)]",
  authButtonSolid: "rounded-full bg-[var(--accent)] px-4 py-1.5 text-[0.8rem] font-semibold uppercase tracking-[1px] text-white transition hover:opacity-90",
  mobileNavContainer: "flex flex-col gap-2 rounded-[18px] border border-[var(--stroke)] bg-[var(--surface)] p-4 text-[0.9rem] uppercase tracking-[1.6px] text-[var(--muted)] shadow-[var(--panel-shadow)]",
  mobileLinkBase: "rounded-full px-4 py-2 transition duration-200",
  mobileLinkActive: "bg-[var(--chip-active-bg)] text-[var(--ink)]",
  mobileLinkInactive: "hover:bg-[var(--surface-strong)] hover:text-[var(--ink)]",
  mobileAuthButtonGhost: "rounded-full border border-[var(--stroke)] px-4 py-2 text-center text-[var(--ink)] transition hover:border-[var(--stroke-strong)]",
  mobileAuthButtonSolid: "rounded-full bg-[var(--accent)] px-4 py-2 text-center font-semibold text-white transition hover:opacity-90",
  headerBase: "fixed top-0 left-0 right-0 z-50 border-b border-[var(--stroke)] bg-[color:var(--surface)]/95 backdrop-blur transition-transform duration-300",
  menuButton: "inline-flex h-8 w-8 items-center justify-center rounded-full border border-[var(--stroke)] text-[var(--ink)] transition duration-200 hover:border-[var(--stroke-strong)] min-[721px]:hidden",
  logoContainer: "flex items-center gap-2",
  title: "lorcana-title text-[1rem] text-shadow-gold",
  actionsContainer: "flex items-center gap-3 min-[721px]:flex",
  mobileContainer: "mx-auto w-full max-w-[1600px] px-6 pb-3 min-[721px]:hidden",
  userAvatar: "flex h-6 w-6 items-center justify-center rounded-full bg-[var(--accent)] text-[0.65rem] font-bold text-white",
  userLinkBase: "flex items-center gap-3 rounded-full px-4 py-2 text-[var(--ink)] transition hover:bg-[var(--surface-strong)]",
  logoutButton: "flex items-center gap-3 rounded-full px-4 py-2 text-[var(--alert-ink)] transition hover:bg-[var(--surface-strong)]",
} as const;
